### ISSUE TITLE
Toolboxes don't have crafting recipes

### ISSUE THREAD

**Issue by OgelGames** [minetest-mods/more_chests#22]
Not sure if this is intentional or not... 😕

**Comment by Megaf** [comment]
@OgelGames can you screenshot the item you are talking about please?

**Comment by OgelGames** [comment]
I'm talking about the toolboxes added in #21: https://github.com/minetest-mods/more_chests/blob/1d59b74c8999d864931a2d25a264b2cb7406b4ef/models/toolbox.lua

The recipes are defined, but not registered.

**Comment by nxet** [comment]
not sure I'm understanding right, but the recipes for the various types of Toolbox are generated in the register_toolbox calls, i.e. at the end of line 28.
can you craft the chest in-game?
thank you

**Comment by OgelGames** [comment]
> the recipes for the various types of Toolbox are generated in the register_toolbox calls, i.e. at the end of line 28.

As I said before:
> The recipes are defined, but not registered.

The recipes still need to be registered with `minetest.register_craft`.

Also I did find this when I looked at the code again:
https://github.com/minetest-mods/more_chests/blob/1d59b74c8999d864931a2d25a264b2cb7406b4ef/utils/base.lua#L37

> can you craft the chest in-game?

No.

**Comment by Megaf** [comment]
If the recipes are already defined, then someone (maybe me) might have forgotten to register them.
I am accepting PRs to fix this :) Please.
