### ISSUE TITLE
Wifi chests have wrong inventory

### ISSUE THREAD

**Issue by OgelGames** [minetest-mods/more_chests#23]
After #21 wifi chests have separate inventories, and act like normal chests, rather than showing the `more_chests:wifi` inventory.  Also they have owner metadata, which they shouldn't.

**Comment by 6r1d** [comment]
I'm interested why that happened as well

**Comment by OgelGames** [comment]
It's because of the generic chest definition, which is not overridden for the wifi chest.

https://github.com/minetest-mods/more_chests/blob/1d59b74c8999d864931a2d25a264b2cb7406b4ef/utils/base.lua#L38-L52

IMO using generic definition function was a bad move for this mod, where most of the chests are very different from each other.

**Comment by Megaf** [comment]
Whoops, not good.
@nxet @SmallJoker

**Comment by Megaf** [comment]
Changes reverted for now.

**Comment by nxet** [comment]
> IMO using generic definition function was a bad move for this mod, where there are only a handful of nodes that are very different from each other.

Well that was the whole point of the rewrite: I wanted to make it easier to extend the mod with custom chests without having to repeat tons of code across the models' implementations.
But I totally understand your point, having nodes with such different game mechanics surely complicates things, and in fact here we are.

I will look into this properly asap, thanks a lot for bringing this up!

**Comment by Megaf** [comment]
@nxet I like your thinking of expanding this in the future and I like the idea. So I already set this significant change in code for out version 2.0 milestone.

@OgelGames I understand your point, but each node can for sure share code between them. Perhaps we just need to reduce the code and make it more elegant and flexible.
