### ISSUE TITLE
shared chest fails to open for users with hyphen in their name

### ISSUE THREAD

**Issue by MCLV-pandorabox** [minetest-mods/more_chests#32]
It seems that the shared chest is not accessible to a player whose name contains a hyphen, such as "player-name."

This is due to the fact that the find method used here interprets the player name as a lua pattern.

suggested change:
elseif shared:find(" " .. name .. " ") then
to: 
elseif shared:find(" " .. name .. " ",1,true) then
in: models/shared.lua:28

**Comment by SmallJoker** [comment]
#33
